### ISSUE TITLE
Selecting the excluded permissions button crashes apol

### ISSUE THREAD

**Issue by d3vilbox** [TresysTechnology/setools#126]
Selecting the exclude permissions button twice in an information flow analysis causes apol to crash. If you select it once nothing happens, so logically you just press it again and boom, down goes Apol.

Backtrace is below.

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/setools-4.0.0b0-py2.7-linux-x86_64.egg/setoolsgui/apol/infoflow.py", line 227, in open_permmap_editor
    self.permmap_editor.show(self.perm_map)
  File "/usr/lib64/python2.7/site-packages/setools-4.0.0b0-py2.7-linux-x86_64.egg/setoolsgui/apol/permmapedit.py", line 84, in show
    self._clear_mappings()
  File "/usr/lib64/python2.7/site-packages/setools-4.0.0b0-py2.7-linux-x86_64.egg/setoolsgui/apol/permmapedit.py", line 141, in _clear_mappings
    self.widgets.clear()
AttributeError: 'list' object has no attribute 'clear'

Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/setools-4.0.0b0-py2.7-linux-x86_64.egg/setoolsgui/apol/infoflow.py", line 227, in open_permmap_editor
    self.permmap_editor.show(self.perm_map)
  File "/usr/lib64/python2.7/site-packages/setools-4.0.0b0-py2.7-linux-x86_64.egg/setoolsgui/apol/permmapedit.py", line 84, in show
    self._clear_mappings()
  File "/usr/lib64/python2.7/site-packages/setools-4.0.0b0-py2.7-linux-x86_64.egg/setoolsgui/apol/permmapedit.py", line 141, in _clear_mappings
    self.widgets.clear()
AttributeError: 'list' object has no attribute 'clear'

**Comment by pebenito** [comment]
That commit should fix it. Please close if so.

**Comment by d3vilbox** [comment]
Tested, and works fine. I am using Fedora 24 btw.
