### ISSUE TITLE
Missing qpol.py file in installation due to setup.py commands order

### ISSUE THREAD

**Issue by fishilico** [TresysTechnology/setools#173]
When installing setools with `python setup.py install`, `setools/policyrep/qpol.py` is not copied to the destination directory. This is because the file is generated in step `build_ext` and Python files are copied beforehand. This issue occurs too when using two commands (like in a packaging script):
```
python setup.py build
python2 setup.py install --root="$pkgdir" --optimize=1 --skip-build
```

A quick search led me to https://stackoverflow.com/questions/12491328/python-distutils-not-include-the-swig-generated-module which is exactly the issue here: `build_py` comes before `build_ext` but with SWIG, the order needs to be the other way round. By the way I tested that running `python setup.py build_ext` before the commands fixes the packaging issue.

To my mind there are two ways of fixing this issue:
* Making sure that `build_ext` comes before `build_py` in `setup.py` execution, which is the answer suggested by the StackOverflow question (like https://git.lumc.nl/mirrors/extractor/commit/4dc84de7a204f06e0151963919d9731faf76c138?view=parallel)
* Documenting in the README that `python setup.py build_ext` needs to be run before installing setools.

For reference, this issue causes programs like `system-config-selinux` to fail with the following message:
```
Traceback (most recent call last):
  File "/usr/share/system-config-selinux/system-config-selinux.py", line 38, in <module>
    import booleansPage
  File "/usr/share/system-config-selinux/booleansPage.py", line 28, in <module>
    import seobject
  File "/usr/lib/python2.7/site-packages/seobject.py", line 34, in <module>
    import sepolicy
  File "/usr/lib/python2.7/site-packages/sepolicy/__init__.py", line 8, in <module>
    import setools
  File "/usr/lib/python2.7/site-packages/setools/__init__.py", line 31, in <module>
    from . import policyrep
  File "/usr/lib/python2.7/site-packages/setools/policyrep/__init__.py", line 26, in <module>
    from .bounds import BoundsRuletype
  File "/usr/lib/python2.7/site-packages/setools/policyrep/bounds.py", line 22, in <module>
    from .qpol import qpol_typebounds_t
ImportError: No module named qpol
```

**Comment by pebenito** [comment]
I'm inclined to leave this as a documentation change, as this is the first I've heard this after all this time.
